catalog:
  astro: ^7.3.3
overrides:
  "astro-simpleanalytics-plugin@0.3.20>astro": "catalog:"
minimumReleaseAgeExclude:
  - '@astrojs/astro2tsx@0.1.1'
  - yargs@18.2.0
allowBuilds:
  esbuild: false
  sharp: true
