name: CI Checks

on:
  pull_request:

jobs:
  biome:
    runs-on: ubuntu-slim
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      
      - name: Set up Biome
        uses: biomejs/setup-biome@v2

      - name: Biome
        run: biome ci
  astro:
    runs-on: ubuntu-slim
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version-file: package.json

      - name: Set up PNPM
        uses: pnpm/action-setup@v5
        with:
          run_install: true
          cache: true
      
      - name: Astro
        run: pnpm run check
